export const Jobs = [
  {
    field: "Tale Marketing Agent",
    name: { agency: " Amr Helmy Design", address: "Maadi, cairo, Egypt" },
    hour: "2 hours ago",
    hours: "Full Time",
    image: "../../../assets/moon.jpeg",
    experience: "Experienced . 3 - 5 Yrs of Exp .",
    details: {
      position: "Service / support. Marketing/PR/Advertising.",
      also: "Sales/Retails. Customer Service.",
      rquirments: [".sales skills", ".Tele marketing"],
    },
  },
  {
    field: "Mechanical maintenance",
    name: { agency: " Amr Helmy Design", address: "Maadi, cairo, Egypt" },
    hour: "14 hours ago",
    hours: "Part Time",
    image: "../../../assets/moon.jpeg",
    experience: "Experienced . 3 - 5 Yrs of Exp .",
    details: {
      position: "Service / support. Marketing/PR/Advertising.",
      also: "Sales/Retails. Customer Service.",
      rquirments: [
        ".sales skills",
        ".Tele marketing",
        ".nice looking",
        "Tooble shooting",
      ],
    },
  },
  {
    field: "Tale Marketing Agent",
    name: { agency: " Amr Helmy Design", address: "Maadi, cairo, Egypt" },
    hour: "2 hours ago",
    hours: "Full Time",
    image: "../../../assets/moon.jpeg",
    experience: "Experienced . 3 - 5 Yrs of Exp .",
    details: {
      position: "Service / support. Marketing/PR/Advertising.",
      also: "Sales/Retails. Customer Service.",
      rquirments: [".sales skills", ".Tele marketing"],
    },
  },
  {
    field: "Tale Marketing Agent",
    name: { agency: " Amr Helmy Design", address: "Maadi, cairo, Egypt" },
    hour: "2 hours ago",
    hours: "Full Time",
    image: "../../../assets/moon.jpeg",
    experience: "Experienced . 3 - 5 Yrs of Exp .",
    details: {
      position: "Service / support. Marketing/PR/Advertising.",
      also: "Sales/Retails. Customer Service.",
      rquirments: [".sales skills", ".Tele marketing"],
    },
  },
  {
    field: "Tale Marketing Agent",
    name: { agency: " Amr Helmy Design", address: "Maadi, cairo, Egypt" },
    hour: "2 hours ago",
    hours: "Full Time",
    image: "../../../assets/moon.jpeg",
    experience: "Experienced . 3 - 5 Yrs of Exp .",
    details: {
      position: "Service / support. Marketing/PR/Advertising.",
      also: "Sales/Retails. Customer Service.",
      rquirments: [".sales skills", ".Tele marketing"],
    },
  },
  {
    field: "Tale Marketing Agent",
    name: { agency: " Amr Helmy Design", address: "Maadi, cairo, Egypt" },
    hour: "2 hours ago",
    hours: "Full Time",
    image: "../../../assets/moon.jpeg",
    experience: "Experienced . 3 - 5 Yrs of Exp .",
    details: {
      position: "Service / support. Marketing/PR/Advertising.",
      also: "Sales/Retails. Customer Service.",
      rquirments: [".sales skills", ".Tele marketing"],
    },
  },
  {
    field: "Tale Marketing Agent",
    name: { agency: " Amr Helmy Design", address: "Maadi, cairo, Egypt" },
    hour: "2 hours ago",
    hours: "Full Time",
    image: "../../../assets/moon.jpeg",
    experience: "Experienced . 3 - 5 Yrs of Exp .",
    details: {
      position: "Service / support. Marketing/PR/Advertising.",
      also: "Sales/Retails. Customer Service.",
      rquirments: [".sales skills", ".Tele marketing"],
    },
  },
  {
    field: "Tale Marketing Agent",
    name: { agency: " Amr Helmy Design", address: "Maadi, cairo, Egypt" },
    hour: "2 hours ago",
    hours: "Full Time",
    image: "../../../assets/moon.jpeg",
    experience: "Experienced . 3 - 5 Yrs of Exp .",
    details: {
      position: "Service / support. Marketing/PR/Advertising.",
      also: "Sales/Retails. Customer Service.",
      rquirments: [".sales skills", ".Tele marketing"],
    },
  },
  {
    field: "Tale Marketing Agent",
    name: { agency: " Amr Helmy Design", address: "Maadi, cairo, Egypt" },
    hour: "2 hours ago",
    hours: "Full Time",
    image: "../../../assets/moon.jpeg",
    experience: "Experienced . 3 - 5 Yrs of Exp .",
    details: {
      position: "Service / support. Marketing/PR/Advertising.",
      also: "Sales/Retails. Customer Service.",
      rquirments: [".sales skills", ".Tele marketing"],
    },
  },
];
