export const tableInfo = [
  {
    id: 1,
    name: "Hakona matata",
    detail: "Chocolate cake with milk",
    price: "500.0$",
    discount: "50 ",
    totalPrice: "250.0$",
    image: "../../../assets/news-01.png",
    category: " ",
  },
  {
    id: 2,
    name: "Hakona matata",
    detail: "Chocolate cake with milk",
    price: "500.0$",
    discount: "50 ",
    totalPrice: "250.0$",
    image: "../../../assets/news-01.png",
    category: " ",
  },
  {
    id: 3,
    name: "Hakona matata",
    detail: "Chocolate cake with milk",
    price: "500.0$",
    discount: "50 ",
    totalPrice: "250.0$",
    image: "../../../assets/news-01.png",
    category: " ",
  },
  {
    id: 4,
    name: "Hakona matata",
    detail: "Chocolate cake with milk",
    price: "500.0$",
    discount: "50 ",
    totalPrice: "250.0$",
    image: "../../../assets/news-01.png",
    category: " ",
  },
  {
    id: 5,
    name: "Hakona matata",
    detail: "Chocolate cake with milk",
    price: "500.0$",
    discount: "50 ",
    totalPrice: "250.0$",
    image: "../../../assets/news-01.png",
    category: " ",
  },
  {
    id: 6,
    name: "Hakona matata",
    detail: "Chocolate cake with milk",
    price: "500.0$",
    discount: "50 ",
    totalPrice: "250.0$",
    image: "../../../assets/news-01.png",
    category: " ",
  },
  {
    id: 7,
    name: "Hakona matata",
    detail: "Chocolate cake with milk",
    price: "500.0$",
    discount: "50 ",
    totalPrice: "250.0$",
    image: "../../../assets/news-01.png",
    category: " ",
  },
  {
    id: 8,
    name: "Hakona matata",
    detail: "Chocolate cake with milk",
    price: "500.0$",
    discount: "50 ",
    totalPrice: "250.0$",
    image: "../../../assets/news-01.png",
    category: " ",
  },
  {
    id: 9,
    name: "Hakona matata",
    detail: "Chocolate cake with milk",
    price: "500.0$",
    discount: "50 ",
    totalPrice: "250.0$",
    image: "../../../assets/news-01.png",
    category: " ",
  },
  {
    id: 10,
    name: "Hakona matata",
    detail: "Chocolate cake with milk",
    price: "500.0$",
    discount: "50 ",
    totalPrice: "250.0$",
    image: "../../../assets/news-01.png",
    category: " ",
  },
  {
    id: 11,
    name: "Hakona matata",
    detail: "Chocolate cake with milk",
    price: "500.0$",
    discount: "50 ",
    totalPrice: "250.0$",
    image: "../../../assets/news-01.png",
    category: " ",
  },
  {
    id: 12,
    name: "Hakona matata",
    detail: "Chocolate cake with milk",
    price: "500.0$",
    discount: "50 ",
    totalPrice: "250.0$",
    image: "../../../assets/news-01.png",
    category: " ",
  },
  {
    id: 13,
    name: "Hakona matata",
    detail: "Chocolate cake with milk",
    price: "500.0$",
    discount: "50 ",
    totalPrice: "250.0$",
    image: "../../../assets/news-01.png",
    category: " ",
  },
  {
    id: 14,
    name: "Hakona matata",
    detail: "Chocolate cake with milk",
    price: "500.0$",
    discount: "50 ",
    totalPrice: "250.0$",
    image: "../../../assets/news-01.png",
    category: " ",
  },
  {
    id: 15,
    name: "Hakona matata",
    detail: "Chocolate cake with milk",
    price: "500.0$",
    discount: "50 ",
    totalPrice: "250.0$",
    image: "../../../assets/news-01.png",
    category: " ",
  },
];
